/*
 * @Author: eds
 * @Date: 2020-07-01 15:22:07
 * @LastEditTime: 2020-09-03 15:41:45
 * @LastEditors: eds
 * @Description:
 * @FilePath: \wz-city-culture-tour\src\store\modules\map\mutation-types.js
 */

export const SET_CURRENT_MAP_TYPE = "SET_CURRENT_MAP_TYPE";
export const SET_MAP_LOADED = "SET_MAP_LOADED";
export const SET_INIT_DATA_LOADED = "SET_INIT_DATA_LOADED";
export const SET_FORCE_MAP_TYPE = "SET_FORCE_MAP_TYPE";
export const SET_IS_INFO_FRAME = "SET_IS_INFO_FRAME";
export const SET_RTMP_LIST = "SET_RTMP_LIST";
export const SET_RTMP_LIST_OTHER = "SET_RTMP_LIST_OTHER";
export const SET_MEDICAL_LIST = "SET_MEDICAL_LIST";
export const SET_MEDICAL_LIST_WITH_GEOMETRY = "SET_MEDICAL_LIST_WITH_GEOMETRY";
export const SET_STATION_LIST = "SET_STATION_LIST";
export const SET_STATION_LIST_WITH_GEOMETRY = "SET_STATION_LIST_WITH_GEOMETRY";
export const SET_BAYONET_LIST = "SET_BAYONET_LIST";
export const SET_BAYONET_LIST_WITH_GEOMETRY = "SET_BAYONET_LIST_WITH_GEOMETRY";
export const SET_TOUR_POINT_LIST = "SET_TOUR_POINT_LIST";
export const SET_TOUR_POINT_LIST_WITH_GEOMETRY = "SET_TOUR_POINT_LIST_WITH_GEOMETRY";
export const SET_HOSPITAL_LIST = "SET_HOSPITAL_LIST";
export const SET_WZ_OVERVIEW_dATA = "SET_WZ_OVERVIEW_dATA";
export const SET_WZ_MEDICAL_DATA = "SET_WZ_MEDICAL_DATA";
export const SET_WZ_TRAFFIC_DATA = "SET_WZ_TRAFFIC_DATA";
export const SET_WZ_TOUR_DATA = "SET_WZ_TOUR_DATA";
export const SET_WZ_CULTURE_DATA = "SET_WZ_CULTURE_DATA";
export const SET_WZ_BASIC_DATA = "SET_WZ_BASIC_DATA";
export const SET_WZ_SOURCE_DATA = "SET_WZ_SOURCE_DATA";
export const SET_WZ_EMERGENCY_DATA = "SET_WZ_EMERGENCY_DATA";
export const SET_FORCE_INDEX = "SET_FORCE_INDEX";
export const SET_FORCE_TIME = "SET_FORCE_TIME";
export const SET_NIGHT_MODE = "SET_NIGHT_MODE";
export const SET_CAMERA_MODE = "SET_CAMERA_MODE";
export const SET_FORCE_TREE_LABEL = "SET_FORCE_TREE_LABEL"
export const SET_FORCE_TRUE_TOPIC_LABEL = "SET_FORCE_TRUE_TOPIC_LABEL"
export const SET_FORCE_TRUE_TOPIC_LABEL_ID = "SET_FORCE_TRUE_TOPIC_LABEL_ID";